const CATEGORY_WORDS: Record<string, readonly string[]> = {
  Nome: [
    'Abel',
    'Ana',
    'António',
    'Bento',
    'Bruna',
    'Bruno',
    'Carla',
    'Carlos',
    'Daniel',
    'Diana',
    'Eduardo',
    'Eva',
    'Fátima',
    'Fernando',
    'Gabriel',
    'Helena',
    'Inês',
    'João',
    'José',
    'Laura',
    'Luís',
    'Manuel',
    'Maria',
    'Nelson',
    'Olga',
    'Paulo',
    'Pedro',
    'Rosa',
    'Sofia',
    'Teresa',
    'Vítor',
  ],
  País: [
    'Afrique du Sud',
    'África do Sul',
    'Allemagne',
    'Alemanha',
    'Angola',
    'Argentina',
    'Austrália',
    'Belgium',
    'Belgique',
    'Bélgica',
    'Brazil',
    'Brésil',
    'Brasil',
    'Cabo Verde',
    'Camarões',
    'Cameroon',
    'Canadá',
    'Canada',
    'Chile',
    'China',
    'Chine',
    'Danemark',
    'Dinamarca',
    'Egypt',
    'Égypte',
    'Egito',
    'Espanha',
    'Estados Unidos',
    'Ethiopia',
    'Éthiopie',
    'Etiópia',
    'France',
    'França',
    'Germany',
    'Ghana',
    'Gana',
    'Guiné',
    'India',
    'Inde',
    'Índia',
    'Italy',
    'Italie',
    'Itália',
    'Japan',
    'Japon',
    'Japão',
    'Kenya',
    'Maroc',
    'Morocco',
    'Marrocos',
    'Mexico',
    'Mexique',
    'México',
    'Mozambique',
    'Moçambique',
    'Namibia',
    'Namibie',
    'Namíbia',
    'Netherlands',
    'Nigeria',
    'Nigéria',
    'Norway',
    'Norvège',
    'Noruega',
    'Países Baixos',
    'Pays-Bas',
    'Portugal',
    'Quénia',
    'Royaume-Uni',
    'United Kingdom',
    'United States',
    'États-Unis',
    'Russia',
    'Russie',
    'Reino Unido',
    'Rússia',
    'São Tomé e Príncipe',
    'Senegal',
    'Sweden',
    'Suède',
    'Suécia',
    'Switzerland',
    'Suisse',
    'Suíça',
    'Tanzania',
    'Tanzânia',
    'Ouganda',
    'Uganda',
    'Venezuela',
    'Zambia',
    'Zambie',
    'Zâmbia',
    'Zimbabwe',
    'Zimbábue',
  ],
  Comida: [
    'Arroz',
    'Bacalhau',
    'Banana',
    'Bife',
    'Bolo',
    'Bread',
    'Cake',
    'Cachupa',
    'Calulu',
    'Carne',
    'Chicken',
    'Churrasco',
    'Eggs',
    'Feijão',
    'Fish',
    'Funge',
    'Gelado',
    'Glace',
    'Hambúrguer',
    'Ice cream',
    'Kizaca',
    'Lasanha',
    'Mandioca',
    'Moamba',
    'Mufete',
    'Ovos',
    'Pain',
    'Pão',
    'Pizza',
    'Poulet',
    'Quiabo',
    'Rice',
    'Riz',
    'Salad',
    'Salada',
    'Soupe',
    'Sopa',
  ],
  Profissão: [
    'Actor',
    'Acteur',
    'Architect',
    'Architecte',
    'Advogado',
    'Arquitecto',
    'Bombeiro',
    'Cabeleireiro',
    'Camionista',
    'Cantor',
    'Dentist',
    'Dentiste',
    'Dentista',
    'Doctor',
    'Engineer',
    'Enfermeiro',
    'Engenheiro',
    'Farmacêutico',
    'Fotógrafo',
    'Ingénieur',
    'Infirmier',
    'Journalist',
    'Journaliste',
    'Jornalista',
    'Lawyer',
    'Médecin',
    'Médico',
    'Motorista',
    'Nurse',
    'Padeiro',
    'Professeur',
    'Professor',
    'Programmer',
    'Programmeur',
    'Programador',
    'Psicólogo',
    'Secretário',
    'Taxista',
    'Teacher',
    'Veterinarian',
    'Vétérinaire',
    'Veterinário',
  ],
  Animal: [
    'Bee',
    'Abeille',
    'Abelha',
    'Águia',
    'Antílope',
    'Baleia',
    'Burro',
    'Cabra',
    'Cão',
    'Cat',
    'Cavalo',
    'Chat',
    'Cheval',
    'Chien',
    'Coelho',
    'Dog',
    'Elephant',
    'Elefante',
    'Éléphant',
    'Foca',
    'Galinha',
    'Gato',
    'Giraffe',
    'Girafa',
    'Hipopótamo',
    'Hiena',
    'Jacaré',
    'Lion',
    'Leão',
    'Monkey',
    'Macaco',
    'Onça',
    'Pato',
    'Peixe',
    'Rato',
    'Rinoceronte',
    'Singe',
    'Tiger',
    'Tigre',
    'Vaca',
    'Zèbre',
    'Zebra',
  ],
  Cidade: [
    'Benguela',
    'Berlim',
    'Brasília',
    'Cabinda',
    'Cairo',
    'Cidade do Cabo',
    'Dundo',
    'Huambo',
    'Lisboa',
    'Lobito',
    'Luanda',
    'Lubango',
    'Malanje',
    'Maputo',
    'Mbanza Congo',
    'Namibe',
    'Nova Iorque',
    'Paris',
    'Porto',
    'Roma',
    'Saurimo',
    'Sumbe',
    'Tóquio',
    'Uíge',
  ],
  Música: [
    'Aleluia',
    'Amor',
    'Despacito',
    'Felicidade',
    'Hello',
    'Imagine',
    'Jerusalema',
    'Perfect',
    'Thriller',
    'Yesterday',
  ],
  Filme: [
    'Avatar',
    'Barbie',
    'Casablanca',
    'Dune',
    'Frozen',
    'Gladiador',
    'Inception',
    'Joker',
    'Matrix',
    'Oppenheimer',
    'Parasita',
    'Rocky',
    'Titanic',
  ],
};

export function normalizeAnswer(answer: string) {
  return answer
    .trim()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLocaleLowerCase('pt-AO');
}

export function startsWithLetter(answer: string, letter: string) {
  return normalizeAnswer(answer).startsWith(normalizeAnswer(letter));
}

export function hasScorableContent(answer: string) {
  const characters = Array.from(normalizeAnswer(answer).replace(/[^\p{L}\p{N}]/gu, ''));

  return characters.length > 1 && new Set(characters).size > 1;
}

export function isKnownAnswer(category: string, answer: string) {
  const normalizedAnswer = normalizeAnswer(answer);

  return (CATEGORY_WORDS[category] ?? []).some(
    (word) => normalizeAnswer(word) === normalizedAnswer,
  );
}
